name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: holdending/Csdhao3095@
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Build
        run: make build
      # - name: Test
      #   run: go test -v ./...
  deploy-to-argo-cd:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Argo CD
        run: |
          # Your deployment script or Argo CD CLI commands here
